/* Generated By:JavaCC: Do not edit this line. MiniJavaExpParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaExpParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FINAL = 5;
  /** RegularExpression Id. */
  int WHILE = 6;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int ELSE = 8;
  /** RegularExpression Id. */
  int PRINT = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int ident = 11;
  /** RegularExpression Id. */
  int number = 12;
  /** RegularExpression Id. */
  int comOP = 13;
  /** RegularExpression Id. */
  int assignOP = 14;
  /** RegularExpression Id. */
  int opsum = 15;
  /** RegularExpression Id. */
  int opprod = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"final\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"print\"",
    "\"int\"",
    "<ident>",
    "<number>",
    "<comOP>",
    "\"=\"",
    "<opsum>",
    "<opprod>",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
  };

}
