/* Generated By:JavaCC: Do not edit this line. PostFixConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PostFixConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int number = 5;
  /** RegularExpression Id. */
  int opsum = 6;
  /** RegularExpression Id. */
  int opprod = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<number>",
    "<opsum>",
    "<opprod>",
    "\"(\"",
    "\")\"",
  };

}
